routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin', 'namespace'=>'Admin'], function() {
   Route::get('/', function() { return view('admin.index'); });

   Route::get('resposta{id}', 'RequisicaoController@responder')->name('requisicoes.resposta');
   Route::post('resposta', 'RequisicaoController@enviaEmail')->name('resposta');

   Route::resource('escolas', 'EscolaController');
   Route::resource('bairros', 'BairroController');
   Route::resource('instituicoes', 'InstituicoesController');
   Route::resource('requisicoes', 'RequisicaoController');
   Route::resource('usuarios', 'UserController');
   Route::get('carrosgraf', 'CarroController@graf')
   ->name('carros.graf');
   Route::get('carrosdestaque/{id}', 'CarroController@destaque')
   ->name('carros.destaque');
   Route::resource('clientes', 'UUserController');
   
   
});

//Route::get('/admin', function() {
//    return view('admin.index');
//});
Auth::routes();



Route::get('home', 'HomeController@index')->name('home');
Route::get('/', function() { return view('index');});
Route::get('mapa', function() { return view('mapa');})->name("mapa");
Route::get('participe', function() { return view('participe');})->name("participe");
Route::get('relatorio', function() { return view('relatorio');})->name('relatorio');
Route::post('enviar_requisicao', 'RequisicaoController@store')->name("enviar_requisicao");

resources/views/admin/carros_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Carros')

@section('content_header')


<h2>Inclusão de Escolas         

  <a href="{{ route('escolas.index') }}" class="btn btn-primary pull-right" role="button">Voltar</a>
</h2>

@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<form method="POST" action="{{ route('escolas.store') }}"
 enctype="multipart/form-data">
        
{{ csrf_field() }}

<div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <label for="nome">Nome da escola</label>
        <input type="text" id="nome" name="nome" required 
               value="{{$reg->nome or old('nome')}}"
               class="form-control">
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <label for="bairro">Bairro</label>
        <select id="bairro" name="bairro_id" class="form-control">
          @foreach($bairros as $b)
            <option value="{{$b->id}}" 
                    {{ ((isset($reg) and $reg->bairro == $b->id) or 
                       old('bairro_id') == $b->id) ? "selected" : "" }}>
                    {{$b->nome}}</option>
          @endforeach
        </select>  
      </div>

      <div class="form-group">
        <label for="endereco">Endereço</label>
        <input type="text" id="endereco" name="endereco" required 
               value="{{$reg->endereco or old('endereco')}}"
               class="form-control">
      </div>
    </div>
  </div>              


  <input type="submit" value="Enviar" class="btn btn-success">
  <input type="reset" value="Limpar" class="btn btn-warning">
</form>

@endsection

resources/views/admin/carros_graf.blade.php
@extends('adminlte::page')

@section('title', 'Grafico de Carros')

@section('content_header')
    <h1>Grafico do Cadastro de Carros
    <a href="{{ route('carros.index') }}" 
       class="btn btn-primary pull-right" role="button">
       Listagem</a>
    </h1>
@endsection

@section('content')

 <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Marcas', 'Nº Veiculos'],

@foreach ($dados as $linha)
{!! "['$linha->marca', $linha->num], " !!}
@endforeach

        ]);

        var options = {
          title: 'Nº de Veiculos por marca',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>

    <div id="piechart_3d" style="width: 900px; height: 500px;"></div>
@endsection

resources/views/admin/carros_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Escolas')

@section('content_header')
    <h1>Cadastro de Escolas
    <a href="{{ route('escolas.create') }}" 
       class="btn btn-primary pull-right" role="button">Novo</a>
    </h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Nome </th>
    <th> Bairro </th>
    <th> Endereço </th>
    <th> Ações </th>
  </tr>  
@forelse($escolas as $e)
  <tr>
    <td> {{$e->nome}} </td>
    <td> {{$e->bairro->nome}} </td>
    <td> {{$e->endereco}} </td>
  
    <td> 
    
        
        <form style="display: inline-block"
              method="post"
              action="{{route('escolas.destroy', $e->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>  &nbsp;&nbsp;
        
    </td>
  </tr>

@empty
  <tr><td colspan=8> Não há Escolas cadastradas ou filtro da pesquisa não 
                     encontrou registros </td></tr>
@endforelse
</table>

@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/clientes_list.blade.php
@extends('adminlte::page')

@section('title', 'Listagem de Clientes')

@section('content_header')
    <h1>Listagem de Clientes</h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Id </th>
    <th> Nome </th>
    <th> Email </th>
    <th> Data </th>
  </tr>  
@forelse($user as $u)
  <tr>
    <td> {{$u->id}} </td>
    <td> {{$u->name}} </td>
    <td> {{$u->email}} </td>
    <td> {{date_format($u->created_at, 'd/m/Y')}} </td>
  </tr>
@empty
  <tr><td colspan=8> Não existem clientes Cadastrados No sistema </td></tr>
@endforelse
</table>
@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/index.blade.php
@extends('adminlte::page')

@section('title', 'Principal')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

resources/views/admin/marcas_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Marcas')

@section('content')

    <div class='col-sm-11'>
        
        <h2> Inclusão de Marcas </h2>
    
    </div>
    <div class='col-sm-1'>
        <a href="{{route('bairros.index')}}" class="btn btn-primary"
           role="button">Voltar</a>
    </div>

    <div class='col-sm-12'>

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        
            <form method="post" action="{{route('bairros.store')}}">
                
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="nome">Nome do Bairro:</label>
                    <input type="text" class="form-control" id="nome"
                            name="nome"
                            
                            required>
                </div>


                        <button type="submit" class="btn btn-primary">Enviar</button>
                        <button type="reset" class="btn btn-warning">Limpar</button>
                    </form>
    </div>


@endsection

resources/views/admin/marcas_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Bairros')

@section('content')
<div class='col-sm-12'>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
    </div>

    <div class='col-sm-11'>
        <h2> Cadastro de Bairros </h2>
    </div>

            <div class="col-sm-1">
                <br>
            <a href="{{route('bairros.create')}}" class="btn btn-info"
               role="button">Novo</a>
            </div>
    <div class='col-sm-12'>



        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($bairros as $b)
                <tr>
                    <td style="text-align: left">{{$b->id}}</td>
                    <td>{{$b->nome}}</td>
                    <td>
                        <form style="display: inline-block"
                              method="post"
                              action="{{route('bairros.destroy', $b->id)}}"
                              onsubmit="return confirm('Confirma Exclusão?')">
                            {{method_field('delete')}}
                            {{csrf_field()}}
                            <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
                        </form> &nbsp;&nbsp;

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
         <div class="col-sm-12"> {{ $bairros->links() }}</div>
    </div>

@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/parceiros_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Parceiros')

@section('content_header')
    <h1>Cadastro de Instituições
    <a href="{{ route('instituicoes.create') }}" 
       class="btn btn-primary pull-right" role="button">Novo</a>
    </h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Nome </th>
    <th> Telefone </th>
    <th> Endereço </th>
    <th> Ações </th>
  </tr>  
@foreach($instituicoes as $i)
  <tr>
    <td> {{$i->nome}} </td>
    <td> {{$i->telefone}} </td>
    <td> {{$i->endereco}} </td>
    <td> 
    
        
        <form style="display: inline-block"
              method="post"
              action="{{route('instituicoes.destroy', $i->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>  &nbsp;&nbsp;
        
    </td>
  </tr>
  
@endforeach
</table>
{{ $instituicoes->links() }}
@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/pconsulta.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Parceiros')

@section('content_header')
    <h1>Consulta de Parceiros</h1>

@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<form method="POST" action="{{route('parceiros.search')}}" enctype="multipart/form-data">

    {{csrf_field()}}

    <div class="row">
        <div class="col-sm-3"> 
            <div class="form-group"> 
                <label for="nome"> Digite a cidade que deseja pesquisar </label>
                <input type="text" id="cidade" name="cidade" required class="form-control">
            </div>
        </div>
    </div>
    <input type="submit" value="Consultar" class="btn btn-success">
    <input type="reset" value="limpar" class="btn btn-warning">
</form>

<br>

<h4> Gerar PDF com todos os Parceiros </h4>
<a href="/relparceiros">Todos os parceiros</a>

@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/proposta_graf.blade.php
@extends('adminlte::page')

@section('title', 'Grafico de Propostas')

@section('content_header')
    <h1>Grafico do Cadastro de Propostas
    <a href="{{ route('proposta.index') }}" 
       class="btn btn-primary pull-right" role="button">
       Listagem</a>
    </h1>
@endsection

@section('content')

 <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Propostas', 'Nº Propostas'],

      @foreach ($dados as $linha)
        {!! "['$linha->mes', $linha->num], " !!}
      @endforeach

        ]);

        var options = {
          title: 'Nº de Propostas por Mês',
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
    </script>

    <div id="piechart_3d" style="width: 900px; height: 500px;"></div>
@endsection

resources/views/admin/propostas_list.blade.php
@extends('adminlte::page')

@section('title', 'Lista de Requisições')

@section('content')

    <div class='col-sm-12'>
        <h2> Requisições </h2>
    </div>
    @if (Session::has('success'))
	<div class="alert alert-success" role="alert">
		<strong>Sucesso:</strong> {{ Session::get('success') }}
	</div>
    @elseif (Session::has('error'))
	<div class="alert alert-danger" role="alert">
		<strong>Erro:</strong> {{ Session::get('error') }}
	</div>
    @endif

@if (count($errors) > 0)
	<div class="alert alert-danger" role="alert">
		<strong>Erros:</strong> 
		<ul>
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
		</ul>
	</div
@endif
    <div class='col-sm-12'>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <table class="table table-striped">
            <tr>
                <th>Código</th>
                <th>Autor da Requisição</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Descrição</th>
                <th>Escola</th>
                <th>Perfil dos Alunos</th>
                <th>Corporação acionada</th>
                <th>Responder</th>
                
            </tr>
            @forelse($requisicoes as $r)
                <tr>
                    <td style="text-align: center">{{$r->id}}</td>
                    <td>{{$r->nomeResponsavel}}</td>
                    <td>{{$r->email}}</td>
                    <td>{{$r->telefone}}</td>
                    <td>{{$r->requisicao}}</td>
                    <td>{{$r->escola->nome}}</td>
                    <td>{{$r->perfilAluno}}</td>
                    <td>{{$r->instituicao->nome}}</td>
                    <td> <a href="{{route('requisicoes.resposta', $r->id)}}"
                        class="btn btn-info"
                        role="button">Responder</a> &nbsp;&nbsp;</td>
                </tr>
            @empty

                <h4>Não existem proposta cadastradas ainda.</h4>

            @endforelse
        </table>
        
    </div>

@endsection

resources/views/admin/relcarros.blade.php
<h1>Revenda Herbie</h1>
<h2>Relatório de Veículos Cadastrados</h2>

<table border=1>
    <tr><td>Modelo</td>
        <td>Ano</td>
        <td>Preço R$:</td>
    </tr>

    @foreach($carros as $c)
        <tr><td>{{$c->modelo}}</td>
            <td>{{$c->ano}}</td>
            <td>{{$c->preco}}</td>
        </tr>
    @endforeach

</table>
        

resources/views/admin/resposta.blade.php
@extends('adminlte::page')

@section('title', 'Resposta')

@section('content_header')
    <h1>Dados da Requisição <b> {{ $requisicoes->id }}</b></h1>
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Dados da Requisição</h3>
      <b>Autor: </b> {{ $requisicoes->nomeResponsavel }}<br>
      <b>E-mail: </b> {{ $requisicoes->email }}<br>
      <b>Telefone: </b> {{ $requisicoes->telefone }} <br>
      <b>Descrição: </b> {{ $requisicoes->requisicao }} <br>
      <br>
      
    </div>
    <div class="col-sm-6">
      <h3>Responder</h3>
      <form action="{{route('resposta')}}" method="post">
        {{ csrf_field() }}
        <input type="hidden" name="id" value="{{ $requisicoes->id }}" s>
        <div class="form-group">
          <label for="nome">Nome do Autor:</label>
          <input id="nome" name="nome" type="text" class="form-control" value="{{ $requisicoes->nomeResponsavel }}" readonly>
        </div>
        <div class="form-group">
          <label for="email">E-mail:</label>
          <input id="email" name="email" type="text" class="form-control" value="{{ $requisicoes->email }}" readonly>
        </div>
        <div class="form-group">
          <label for="email">Telefone:</label>
          <input id="telefone" name="telefone" type="text" class="form-control" value="{{ $requisicoes->telefone }}" readonly>
        </div>
        <div class="form-group">
          <label for="mensagem">Resposta:</label>
          <textarea rows="4" cols="50" id="mensagem" name="mensagem" class="form-control"></textarea>
        </div>
        <input type="submit" class="btn btn-success" value="enviar">
      </form>
    </div>
  </div>
</div>

@endsection

resources/views/admin/usuarios_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Carros')

@section('content_header')
    <h1>Cadastro de Usuários
    <a href="{{ route('register') }}" 
       class="btn btn-primary pull-right" role="button">Novo</a>
    </h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Id </th>
    <th> Nome </th>
    <th> Email </th>
    <th> Data </th>
    <th>Ações </th>
  </tr>  
@forelse($user as $u)
  <tr>
    <td> {{$u->id}} </td>
    <td> {{$u->name}} </td>
    <td> {{$u->email}} </td>
    <td> {{date_format($u->created_at, 'd/m/Y')}} </td>
    <td> 
        <a href="" 
            class="btn btn-warning btn-sm" title="Alterar"
            role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
        <form style="display: inline-block"
              method="post"
              action="{{route('usuarios.destroy', $u->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>  
    </td>
  </tr>
@empty
  <tr><td colspan=8> Não existem usuarios Cadastrados No sistema </td></tr>
@endforelse
</table>
@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection